version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/falirandria/everest-demo/mqtt-server:${TAG}
    logging:
      driver: none

  manager:
    image: ghcr.io/falirandria/everest-demo/manager:${TAG}
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    working_dir: /ext/source/tests
    entrypoint: "sh ./run-test.sh; echo 'Ignoring result since tests are known to fail'"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    extra_hosts:
      - "host.docker.internal:host.docker.internal"
