active_modules:
  powersupply_dc:
    module: JsDCSupplySimulator
    config_implementation:
      main:
        max_power: 250000
        max_current: 400
  car_simulator:
    module: JsCarSimulator
    config_module:
      connector_id: 1
      auto_enable: true
      auto_exec: false
      auto_exec_commands: sleep 1;iec_wait_pwr_ready;sleep 1;draw_power_regulated 16,3;sleep 30;unplug
      dc_target_current: 400
      dc_target_voltage: 400
      dc_max_power_limit: 200000